name: 'PR to master branch from develop with release tag'

on:
  # Triggered manually
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true
      targetEnv:
        description: "Target Environment"
        required: true
        type: choice
        options:
        - DEV
        - PROD
  # Triggered by release-nocodb.yml
  workflow_call:
    inputs:
      tag:
        description: "Tag"
        required: true
        type: string
      targetEnv:
        description: "Target Environment"
        required: true
        type: string
        
jobs:
  pr-to-master:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'triggering pr-to-master'
          echo ${{ github.event.inputs.tag || inputs.tag }}
          echo ${{ github.event.inputs.targetEnv || inputs.targetEnv }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: develop

      - name: Create Pull Request
        if: ${{ github.event.inputs.targetEnv == 'PROD' || inputs.targetEnv == 'PROD' }}
        id: cpr
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          signoff: true
          base: 'master'
          branch: 'release/${{ github.event.inputs.tag || inputs.tag }}'
          delete-branch: true
          title: '${{ github.event.inputs.tag || inputs.tag }} Pre-release'
          labels: |
            Bot: Automated PR
      - name: Check outputs
        if: ${{ github.event.inputs.targetEnv == 'PROD' || inputs.targetEnv == 'PROD' }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - name: automerge
        if: ${{ github.event.inputs.targetEnv == 'PROD' || inputs.targetEnv == 'PROD' }}
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
           PULL_REQUEST: "${{ steps.cpr.outputs.pull-request-number }}"