name: "Release : Draft Notes"

on:
  # Triggered manually
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true
      prev_tag:
        description: "Previous Tag"
        required: true
  # Triggered by release-nocodb.yml
  workflow_call:
    inputs:
      tag:
        description: "Tag"
        required: true
        type: string
      prev_tag:
        description: "Previous Tag"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Create tag
        id: get-sha
        run: |
          echo 'triggering release-draft'
          echo ${{ github.event.inputs.tag || inputs.tag }}
          echo ${{ github.event.inputs.prev_tag || inputs.prev_tag }}
          echo $(git rev-parse HEAD~2)
          TARGET_SHA=$(git rev-parse HEAD~2)
          echo "::set-output name=TARGET_SHA::${TARGET_SHA}"
          echo "${{steps.get-sha.outputs.TARGET_SHA}}"
          # git config user.name "GitHub Actions Bot"
          # git config user.email "<>"
          # git tag -a "${{ github.event.inputs.tag || inputs.tag }}" ${TARGET_SHA} -m "${{ github.event.inputs.tag || inputs.tag }} Release"
          # git push origin --tags
      
      
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ github.event.inputs.tag || inputs.tag }}"
          message: "${{ github.event.inputs.tag || inputs.tag }} Release"
          commit_sha: "${{steps.get-sha.outputs.TARGET_SHA}}"

    #   - uses: actions/setup-node@v2
    #     with:
    #       node-version: 14
    #   - run: "npx github-release-notes@0.17.2  release --token ${{ secrets.GITHUB_TOKEN }}  --draft --tags ${{ github.event.inputs.tag || inputs.tag }}..${{ github.event.inputs.prev_tag || inputs.prev_tag }}"
