name: 'NocoDB Nightly Dev Release'

on:
  # Triggered manually
  workflow_dispatch:
    inputs:
      tag:
        description: "Target Tag"
        required: true
  schedule:
    # at the end of every day
    - cron: '0 0 * * *'
jobs:
  # enrich tag for nightly auto release
  set-tag:
    runs-on: 'ubuntu-20.04'
#     if: (github.event_name == 'schedule')
    steps:
      - id: tag-step
        run: |
          # Get current date
          export CURRENT_DATE=$(date +"%Y%m%d")
          # Set the tag
          echo "::set-output name=NIGHTLY_BUILD_TAG::nightly-${CURRENT_DATE}"
          # Verify the tag
          echo "${{ steps.tag-step.outputs.NIGHTLY_BUILD_TAG }}"
#   Build docker image and push to docker hub
  release-docker:
    uses: ./.github/workflows/release-docker.yml
    with:
      tag: $ {{ jobs.set-tag.steps.tag-step.NIGHTLY_BUILD_TAG }}
#       tag: ${{ github.event.inputs.tag ||  jobs.set-tag.steps.tag-step.NIGHTLY_BUILD_TAG }}
