name: 'Test PR'

on:
  pull_request_target:
    # opened: pull request is created
    # reopened: closed pull request is reopened
    # synchronize: commit(s) pushed to the pull request
    # ready_for_review: non PR release
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - "packages/nocodb-sdk/**"
      - "packages/nc-gui/**"
      - "packages/nc-plugin/**"
      - "packages/nocodb/**"
jobs:
  set-tag:
    runs-on: 'ubuntu-latest'
    steps:
      - name: set-tag
        id: tag-step
        run: |
          echo "${{ secrets.DUMMY_SECRET }}"
          echo "${{ github.event.pull_request.draft }}"
          echo "${{ github.event.pull_request_target.draft }}"
